### ISSUE TITLE
feat: add badge component

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-ios#17]
**New component**

Add badge component.

**Documentation links**

- [Documentation](https://www.decathlon.design/726f8c765/p/465f7c-badge-beta/b/5496b9)
- [Figma](https://www.figma.com/file/cmZCNVet64UlDNnDDd4hDV/Vitamin-iOS-14-UI-kit-v0?node-id=1001%3A3247)

**Comment by daniel-dumortier** [comment]
closed by #
