### ISSUE TITLE
feat: add snackbar component

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-ios#21]
**New component**

Add snackbar component.

**Documentation links**

- [Documentation](https://www.decathlon.design/726f8c765/p/798580-snackbar/b/83feb7)
- [Figma](https://www.figma.com/file/cmZCNVet64UlDNnDDd4hDV/Vitamin---iOS-14-UI-kit-(v0)?node-id=1365%3A5080)

**Comment by daniel-dumortier** [comment]
@lauthieb If we link this issue with my PR, we should remove the SwiftUI tag, and recreate another issue for the SwiftUI version of the component.
