### ISSUE TITLE
refactor: change placeholder color 

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-ios#32]
**Is your request related to a problem? Please describe.**

**Describe the solution you'd like**

- Placeholder on mobile libraries should be in Content tertiary instead of content inactive

**Comment by daniel-dumortier** [comment]
@GaspardMathon : If you're talking about placeHolder in Vitamin text fields, I am not sure this issue is relevant.
Here is a snippet of the code to put placeholder color which shows we use content tertiary (with a "disabled" opacity if the field is disabled) : 

```swift
var placeholderColor: UIColor {
        if self == .disabled {
            return VitaminColor.Core.Content.tertiary.disabledColor()
        } else {
            return VitaminColor.Core.Content.tertiary
        }
    }
```
