### ISSUE TITLE
refactor: improve color of hover tertiary

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-ios#51]
**Is your request related to a problem? Please describe.**

- `hover tertiary` color has been improved. The color need to be updated in the lib.

**Describe the solution you'd like**

- Change the value of the `hover tertiary` color

**Additional context**

- [Button component figma](https://www.figma.com/file/cmZCNVet64UlDNnDDd4hDV/Vitamin---iOS-14-UI-kit-(v0)?node-id=11%3A0)
- [Jira issue](https://decathlon.atlassian.net/jira/software/projects/DSRUN/boards/2922?selectedIssue=DSRUN-65)

**Comment by daniel-dumortier** [comment]
Checked in the code, and it is already up to date with Figma in 0.5.0 :
```swift
extension VitaminColor.Core {
    public enum Hover {
        [...]

        public static var tertiary: UIColor {
            let components = VitaminColor.Core.Background.brandSecondary.hslComponents()
            return UIColor(hue: components.hue,
                           saturation: components.saturation,
                           brightness: components.lightness * 0.95,
                           alpha: 1)
        }
```

I close the issue
