### ISSUE TITLE
refactor: edit card gradient on full-image variant 

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-ios#69]
**Is your request related to a problem? Please describe.**

- On card with gradient, contrast is not enough on text (2.83).

**Describe the solution you'd like**

- Let’s improve it → Gradient has to be full height

**Additional context**

- [Figma](https://www.figma.com/file/cmZCNVet64UlDNnDDd4hDV/Vitamin---iOS-14-UI-kit-(v0)?node-id=771%3A2392)

**Comment by lauthieb** [comment]
Card isn't yet developed.
