### ISSUE TITLE
feat: apply shadows guideline

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-ios#9]
**Is your request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

Apply shadows guideline.

**Additional context**

Documentation: https://www.decathlon.design/726f8c765/p/5522fa-shadows-beta
Figma: https://www.figma.com/file/cmZCNVet64UlDNnDDd4hDV/?node-id=417%3A0

**Comment by daniel-dumortier** [comment]
closed by #4
